apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-messaging-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-messaging-blue
  template:
    metadata:
      labels:
        app: django-messaging-blue
    spec:
      containers:
        - name: django
          image: django-messaging:latest
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: django-messaging-service
spec:
  selector:
    app: django-messaging
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
