#!/bin/bash

echo "Deploying blue version..."
kubectl apply -f blue_deployment.yaml

echo "Deploying green version..."
kubectl apply -f green_deployment.yaml

echo "Switching service to green..."
kubectl apply -f kubeservice.yaml

echo "Checking logs from green version..."
kubectl get pods -l app=django-messaging-green
kubectl logs $(kubectl get pods -l app=django-messaging-green -o name | head -n 1)
